### ISSUE TITLE
关于dnsmos计算的疑问

### ISSUE THREAD

**Issue by Zac1ary** [hit-thusz-RookieCJ/dns_mos_calculate#1]
您好，我是初学者在调用这个计算的时候一直显示retry_1，能否请教一下原因

**Comment by RookieJunChen** [comment]
Online是微软那边提供的接口来算DNS_MOS，一直retry估计是那边的接口出了问题;
建议采用Offline的形式来跑跑看？

**Comment by Zac1ary** [comment]
感谢您的建议，我用local来跑一个baseline结果是这样的
The average SIG, BAK and OVR MOS for dnsmos_p835_inference_sig_bak_ovr_test is 3.58, 3.48, 2.92
我想问一下代码中SIG BAK OVR是什么意思啊 我没有找到资料，还要麻烦问一下您最后DNS_MOS应该怎么计算

**Comment by RookieJunChen** [comment]
SIG你可以理解为是评价人声质量的，BAK你可以理解为是评价噪音消除程度的，OVR你可以理解为是评价二者结合的整体情况的。
最后如果你需要单个的DNS_MOS，应该取OVR的。

**Comment by Zac1ary** [comment]
> SIG你可以理解为是评价人声质量的，BAK你可以理解为是评价噪音消除程度的，OVR你可以理解为是评价二者结合的整体情况的。 最后如果你需要单个的DNS_MOS，应该取OVR的。

好的好的，我做的是另一个任务用到了这个指标，我现在明白了！谢谢你，祝你科研顺利！！！
