### ISSUE TITLE
Offline 的bak_ovr.onnx 和 sig.onnx 是怎么来的？

### ISSUE THREAD

**Issue by zuowanbushiwo** [hit-thusz-RookieCJ/dns_mos_calculate#2]
你好
      最近在做语音降噪，请问你的这两个模型是什么训练出来的？谢谢！

**Comment by RookieJunChen** [comment]
你好，这个是微软DNS Challenge仓库提供的DNSMOS分计算的模型。我是为了方便自己用，改进后放在了自己的github。具体模型的训练方法可以参考：[DNSMOS](https://arxiv.org/abs/2010.15258)。

**Comment by zuowanbushiwo** [comment]
@hit-thusz-RookieCJ 好的，非常感谢，我一直以为只有云端的web api了。
