### ISSUE TITLE
请问有 bak_ovr.onnx 和 sig.onnx 的模型和训练代码吗

### ISSUE THREAD

**Issue by zuowanbushiwo** [hit-thusz-RookieCJ/dns_mos_calculate#3]
你好
       请问有这两个模型的训练代码吗？这个模型可以修改成按帧的计算吗？这样做准确度会下降吗？
谢谢！

**Comment by RookieJunChen** [comment]
1. 训练代码微软他们应该是没有公布的，另外我觉得复现这个模型主要的难度在于数据（他们找人打的MOS分，也应该是没公布的）
2. 按帧计算我没试过，不过根据这个原理来看（target是人打的MOS分，人耳应该判别不太出帧级别的效果吧？），我个人认为应该是不太work的。

**Comment by zuowanbushiwo** [comment]
@hit-thusz-RookieCJ 
非常感谢回复。在我们实际场景(比如视频会议)使用降噪算法是按帧进行，我就想也按帧的进行检测一下，这样可以实时检测，后面就可以配合传统的降噪算法做一些补救。 如果不能按帧做，这个最短语音是多少是多长？谢谢！

**Comment by RookieJunChen** [comment]
我个人觉得，按照他的原理来说，用人耳听的话是不是至少得0.5s-1s以上才能辨别出来（更何况他这个模型的训练数据应该不止这么点长度）。另外，我这边的实践经验是，这个DNSMOS在带混响的情况下分数很不准确。
我觉得如果你要做的话，是不是可以训一个帧级别的噪声检测模型拿来用？（我印象里是有那种实时的帧级别音频事件检测模型的，可能标一下数据拿来改改就能用？）

**Comment by zuowanbushiwo** [comment]
非常感谢大佬的指点。 
这个DNSMOS在带混响的情况下分数很不准确。 除了DNSMOS 外，还有其他开源的吗？[NISQA](https://github.com/hit-thusz-RookieCJ/my_NISQA) 可以吗？这种数据确实挺难搞的。
帧级别的噪声检测模型 -> 这个有没有可参考的工程，我也找找。

**Comment by RookieJunChen** [comment]
NISQA检测语音质量来说相对不错，但我不确定他能不能检测帧级别的。抱歉，帧级别的工程在我所知范围内我是不知道有没有的

**Comment by zuowanbushiwo** [comment]
好的，感谢。祝您一切安好！
