### ISSUE TITLE
关于模型来源的疑问

### ISSUE THREAD

**Issue by wuzhuohong** [hit-thusz-RookieCJ/dns_mos_calculate#4]
请问下，这个模型是怎么得到的啊，是对应哪篇论文呀，线上和线下的分数对比怎么样呢？

**Comment by RookieJunChen** [comment]
微软的DNSMOS，我的master分支对应的是旧版本（微软一直在更新他们的DNSMOS的模型）的DNSMOS分数，能和如DeepFilterNet等论文中所写的DNS MOS分数对齐。我这里的这个仓库是为了保存我自己的小改动来方便用的，如果你需要看原版可见：https://github.com/microsoft/DNS-Challenge/tree/master/DNSMOS
至于线上版本，我目前已经不用了，不太确定现在还能不能用或是微软线上的模型是否有更新。

**Comment by wuzhuohong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的感谢回复！

    在2023年05月17日 19:21，Jun ***@***.***> 写道： 



微软的DNSMOS，我的master分支对应的是旧版本（微软一直在更新他们的DNSMOS的模型）的DNSMOS分数，能和如DeepFilterNet等论文中所写的DNS MOS分数对齐。我这里的这个仓库是为了保存我自己的小改动来方便用的，如果你需要看原版可见：https://github.com/microsoft/DNS-Challenge/tree/master/DNSMOS
至于线上版本，我目前已经不用了，不太确定现在还能不能用或是微软线上的模型是否有更新。
